### ISSUE TITLE
Build error: missing lib ooo_suite.jar

### ISSUE THREAD

**Issue by fouric** [XanTheDragon/Spiral-Knights-Animator-Tools#12]
Attempting to build the project in Eclipse 4.8.0 on Linux results in a build error: "Project 'Spiral Knights Animator Tools' is missing required library: 'src/libs/ooo_suite.jar'"

Inspection of src/libs reveals that the referenced library is indeed missing. Do I need to download it from the Spiral Knights website somewhere?

**Comment by XanTheDragon** [comment]
Hey I'm sorry I'm so late! I've been idle and I entirely missed this!

`ooo_suite.jar` is a custom jar I packed that contains all four core libraries for model usage (clyde/narya/nenya/vilya).

The error you're getting was an oversight on my part where I forgot to update the contents of `src/libs` (it still includes the four libraries instead of my merged ooo_suite.jar).

I've resolved this issue and if you redownload the repo and overwrite your libs folder with the new one it should be good to go.
